### ISSUE TITLE
[Request] Bosch/Siemens Home Connect

### ISSUE THREAD

**Issue by DJay-X** [tobilarscheid/homebridge-conrad-connect#1]
@tobilarscheid  First of all, thanks for your work, the time you are investing and for sharing your plugin with the community. 👍 

I was hoping for a plugin like this, because of the possibility to integrate my Bosch Coffee Maker [CTL636ES6](https://www.bosch-home.com/de/produktliste/kaffeemaschinen/einbau-kaffeevollautomaten/CTL636ES6) with Home Connect via Homebridge to HomeKit.

I have no experience with Conrad Connect but they also seem to have the [Bosch Home Connect service available](https://conradconnect.de/de/brand/home-connect).

If there is anything I can do to help integrate Home Connect to your plugin, please of course let me know. But not a developer, though. ;) 

Thanks again.

**Comment by tobilarscheid** [comment]
Hi @DJay-X, thanks for your interest in our work and your positive comment :-)

Your request sounds exactly like what we envision for this plugin: Make all of the connectivity options Conrad Connect offers available in HomeKit through Homebridge.

Currently, we are working with the Conrad Connect team to understand all of the platform's technical possibilities and get our service released as soon as possible. The first device category we are integrating is smart lightbulbs (simply just because we have a lot of them at hand to test the integration ;-) ), but extension to other categories is definitely possible and on our roadmap. Only thing we would need to figure out is where to get a smart coffee maker ;-)

Anyways, we will keep you updated through this issue and will let you know whenever you can support us with your expertise.

Best regards,

Tobi

**Comment by DJay-X** [comment]
That sounds fantastic. Thanks to you all guys.
If you need some more testers or inspiration, I am confident that there are a few more enthusiasts in the community that are willing to help. As one of the moderators of the SmartApfel Forum, I would love to welcome you there.  https://forum.smartapfel.de/forum/thread/3681-homebridge-conrad-connect/
Till then, all the best to you.

**Comment by kmeinh** [comment]
Hi @DJay-X, thank you for the Request.

I think this issue could be fixed if we can integrate "Buttons" from the Conrad-Connect-Dashboard.
That would solve the problem for all kind of Devices in general, without implementing each device on its own.

So by fixing #4 you would be able to interact with your coffee maker using the "automation" Dashboard from Conrad-Connect.

We will keep this thread up to date when we get further news/infos on any of these Issues.

Best regards,

Konstantin

**Comment by DJay-X** [comment]
@konDeichmann Thanks a lot for your brain work. 👍 
Maybe it is also possible to reflect the actual state of the device (Coffee Maker). On or off. 
Not sure if the HomeConnect API does this with Conrad Connect.
At the moment I am just using IFTTT Webhook to turn the machine on and off or to select a coffee world program which is also only a switch to choose a coffee specialty like Flat White, Americao etc. This buttons only switch on and after 3 seconds back off so that they can be used over and over. In Eve for HomeKit App it looks like this. Actual state of the machine, when switched on/off on the device itself or with the Home Connect App, is unfortunately not reflecting to HomeKit.
I was hoping this would be possible with Conrad Connect.

Thanks again to you guys.

```
{
            "platform": "IFTTT",
            "name": "IFTTT",
            "makerkey": "xxxxxxxxxxxxxxxxxxxx",
            "accessories": [
                {
                    "name": "Kaffeemaschine",
                    "buttons": [
                        {
                            "caption": "Kaffeemaschine",
                            "triggerOn": "coffee_on",
                            "triggerOff": "coffee_off",
                            "stateful": true,
                            "delayOn": 1,
                            "delayOff": 1
                        },
                        {
                            "caption": "Americano",
                            "trigger": "Americano"
                        },
                        {
                            "caption": "Latte Macchiato",
                            "trigger": "Latte Macchiato"
                        },
                        {
                            "caption": "Flat White",
                            "trigger": "Flat White"
                        },
                        {
                            "caption": "Espresso",
                            "trigger": "Espresso"
                        },
                        {
                            "caption": "Kaffee stopp",
                            "trigger": "coffee_stop"
                        }
                    ]
                },
```

![Napkin 2 14 08 19, 10 40 35 PM](https://user-images.githubusercontent.com/3874239/63054746-c0eba380-bee4-11e9-8e56-8d156effc2b3.png)

**Comment by Nastras** [comment]
Hello, are there any news on the implementation?

Thanks!

**Comment by tobilarscheid** [comment]
Hi @Nastras, thanks for your interest. We are still in the process of releasing our first version of the service on the conrad connect platform, expect the release any day soon!

**Comment by Nastras** [comment]
That sounds great. Many thanks for the quick answer!

**Comment by Kohle81** [comment]
Hi @tobilarscheid,

this plugin sounds good!
The Home Connect integration would be great for my coffee maker!

Greetz Manuel

**Comment by Nastras** [comment]
> Hi @Nastras, thanks for your interest. We are still in the process of releasing our first version of the service on the conrad connect platform, expect the release any day soon!

Hello @tobilarscheid , it's been a few days, so I wanted to ask again what the status is?

I hope you have good news for us 😀?

**Comment by jangt15** [comment]
Hi guys,
Are there any news when Homeconnect will be implemented?

**Comment by DJay-X** [comment]
{deprecated}
